[language.haskell]
filetypes = ["haskell"]
roots = ["Setup.hs", "stack.yaml", "*.cabal"]
command = "haskell-language-server-wrapper"
args = ["--lsp"]

[language.terraform]
filetypes = ["terraform"]
roots = ["*.tf"]
command = "terraform-lsp"
args = ["serve"]
